/*
AIOZ-AI-PLATFORM API

Testing ApiKeyModelVersioningAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package myclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_myclient_ApiKeyModelVersioningAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ApiKeyModelVersioningAPIService ApiKeyModelIdVersioningDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.ApiKeyModelVersioningAPI.ApiKeyModelIdVersioningDelete(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApiKeyModelVersioningAPIService ApiKeyModelIdVersioningGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.ApiKeyModelVersioningAPI.ApiKeyModelIdVersioningGet(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApiKeyModelVersioningAPIService ApiKeyModelIdVersioningListGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.ApiKeyModelVersioningAPI.ApiKeyModelIdVersioningListGet(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApiKeyModelVersioningAPIService ApiKeyModelIdVersioningPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.ApiKeyModelVersioningAPI.ApiKeyModelIdVersioningPut(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
