/*
AIOZ-AI-PLATFORM API

Testing ApiKeyRepositoryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package aiozaiplatformgosdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/thinhtruongnguyen/publish-go"
)

func Test_aiozaiplatformgosdk_ApiKeyRepositoryAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ApiKeyRepositoryAPIService ApiKeyRepositoryOwnerUsernameRepositoryNameCommitHistoryGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ownerUsername string
		var repositoryName string

		resp, httpRes, err := apiClient.ApiKeyRepositoryAPI.ApiKeyRepositoryOwnerUsernameRepositoryNameCommitHistoryGet(context.Background(), ownerUsername, repositoryName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
