/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozaiplatformgosdk

import (
	"encoding/json"
)

// checks if the ResponseGetTaskStatisticsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseGetTaskStatisticsData{}

// ResponseGetTaskStatisticsData struct for ResponseGetTaskStatisticsData
type ResponseGetTaskStatisticsData struct {
	TotalCost *int32 `json:"total_cost,omitempty"`
	TotalFailed *int32 `json:"total_failed,omitempty"`
	TotalRequest *int32 `json:"total_request,omitempty"`
	TotalSuccess *int32 `json:"total_success,omitempty"`
}

// NewResponseGetTaskStatisticsData instantiates a new ResponseGetTaskStatisticsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseGetTaskStatisticsData() *ResponseGetTaskStatisticsData {
	this := ResponseGetTaskStatisticsData{}
	return &this
}

// NewResponseGetTaskStatisticsDataWithDefaults instantiates a new ResponseGetTaskStatisticsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseGetTaskStatisticsDataWithDefaults() *ResponseGetTaskStatisticsData {
	this := ResponseGetTaskStatisticsData{}
	return &this
}

// GetTotalCost returns the TotalCost field value if set, zero value otherwise.
func (o *ResponseGetTaskStatisticsData) GetTotalCost() int32 {
	if o == nil || IsNil(o.TotalCost) {
		var ret int32
		return ret
	}
	return *o.TotalCost
}

// GetTotalCostOk returns a tuple with the TotalCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetTaskStatisticsData) GetTotalCostOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCost) {
		return nil, false
	}
	return o.TotalCost, true
}

// HasTotalCost returns a boolean if a field has been set.
func (o *ResponseGetTaskStatisticsData) HasTotalCost() bool {
	if o != nil && !IsNil(o.TotalCost) {
		return true
	}

	return false
}

// SetTotalCost gets a reference to the given int32 and assigns it to the TotalCost field.
func (o *ResponseGetTaskStatisticsData) SetTotalCost(v int32) {
	o.TotalCost = &v
}

// GetTotalFailed returns the TotalFailed field value if set, zero value otherwise.
func (o *ResponseGetTaskStatisticsData) GetTotalFailed() int32 {
	if o == nil || IsNil(o.TotalFailed) {
		var ret int32
		return ret
	}
	return *o.TotalFailed
}

// GetTotalFailedOk returns a tuple with the TotalFailed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetTaskStatisticsData) GetTotalFailedOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalFailed) {
		return nil, false
	}
	return o.TotalFailed, true
}

// HasTotalFailed returns a boolean if a field has been set.
func (o *ResponseGetTaskStatisticsData) HasTotalFailed() bool {
	if o != nil && !IsNil(o.TotalFailed) {
		return true
	}

	return false
}

// SetTotalFailed gets a reference to the given int32 and assigns it to the TotalFailed field.
func (o *ResponseGetTaskStatisticsData) SetTotalFailed(v int32) {
	o.TotalFailed = &v
}

// GetTotalRequest returns the TotalRequest field value if set, zero value otherwise.
func (o *ResponseGetTaskStatisticsData) GetTotalRequest() int32 {
	if o == nil || IsNil(o.TotalRequest) {
		var ret int32
		return ret
	}
	return *o.TotalRequest
}

// GetTotalRequestOk returns a tuple with the TotalRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetTaskStatisticsData) GetTotalRequestOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalRequest) {
		return nil, false
	}
	return o.TotalRequest, true
}

// HasTotalRequest returns a boolean if a field has been set.
func (o *ResponseGetTaskStatisticsData) HasTotalRequest() bool {
	if o != nil && !IsNil(o.TotalRequest) {
		return true
	}

	return false
}

// SetTotalRequest gets a reference to the given int32 and assigns it to the TotalRequest field.
func (o *ResponseGetTaskStatisticsData) SetTotalRequest(v int32) {
	o.TotalRequest = &v
}

// GetTotalSuccess returns the TotalSuccess field value if set, zero value otherwise.
func (o *ResponseGetTaskStatisticsData) GetTotalSuccess() int32 {
	if o == nil || IsNil(o.TotalSuccess) {
		var ret int32
		return ret
	}
	return *o.TotalSuccess
}

// GetTotalSuccessOk returns a tuple with the TotalSuccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetTaskStatisticsData) GetTotalSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalSuccess) {
		return nil, false
	}
	return o.TotalSuccess, true
}

// HasTotalSuccess returns a boolean if a field has been set.
func (o *ResponseGetTaskStatisticsData) HasTotalSuccess() bool {
	if o != nil && !IsNil(o.TotalSuccess) {
		return true
	}

	return false
}

// SetTotalSuccess gets a reference to the given int32 and assigns it to the TotalSuccess field.
func (o *ResponseGetTaskStatisticsData) SetTotalSuccess(v int32) {
	o.TotalSuccess = &v
}

func (o ResponseGetTaskStatisticsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseGetTaskStatisticsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalCost) {
		toSerialize["total_cost"] = o.TotalCost
	}
	if !IsNil(o.TotalFailed) {
		toSerialize["total_failed"] = o.TotalFailed
	}
	if !IsNil(o.TotalRequest) {
		toSerialize["total_request"] = o.TotalRequest
	}
	if !IsNil(o.TotalSuccess) {
		toSerialize["total_success"] = o.TotalSuccess
	}
	return toSerialize, nil
}

type NullableResponseGetTaskStatisticsData struct {
	value *ResponseGetTaskStatisticsData
	isSet bool
}

func (v NullableResponseGetTaskStatisticsData) Get() *ResponseGetTaskStatisticsData {
	return v.value
}

func (v *NullableResponseGetTaskStatisticsData) Set(val *ResponseGetTaskStatisticsData) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseGetTaskStatisticsData) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseGetTaskStatisticsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseGetTaskStatisticsData(val *ResponseGetTaskStatisticsData) *NullableResponseGetTaskStatisticsData {
	return &NullableResponseGetTaskStatisticsData{value: val, isSet: true}
}

func (v NullableResponseGetTaskStatisticsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseGetTaskStatisticsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


