/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozaiplatformgosdk

import (
	"encoding/json"
)

// checks if the ResponseSuccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseSuccessResponse{}

// ResponseSuccessResponse struct for ResponseSuccessResponse
type ResponseSuccessResponse struct {
	Message *string `json:"message,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewResponseSuccessResponse instantiates a new ResponseSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseSuccessResponse() *ResponseSuccessResponse {
	this := ResponseSuccessResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// NewResponseSuccessResponseWithDefaults instantiates a new ResponseSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseSuccessResponseWithDefaults() *ResponseSuccessResponse {
	this := ResponseSuccessResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseSuccessResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseSuccessResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseSuccessResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseSuccessResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponseSuccessResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseSuccessResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponseSuccessResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ResponseSuccessResponse) SetStatus(v string) {
	o.Status = &v
}

func (o ResponseSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseSuccessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResponseSuccessResponse struct {
	value *ResponseSuccessResponse
	isSet bool
}

func (v NullableResponseSuccessResponse) Get() *ResponseSuccessResponse {
	return v.value
}

func (v *NullableResponseSuccessResponse) Set(val *ResponseSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseSuccessResponse(val *ResponseSuccessResponse) *NullableResponseSuccessResponse {
	return &NullableResponseSuccessResponse{value: val, isSet: true}
}

func (v NullableResponseSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


