/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozaiplatformgosdk

import (
	"encoding/json"
)

// checks if the ResponseApiKeyInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseApiKeyInfoResponse{}

// ResponseApiKeyInfoResponse struct for ResponseApiKeyInfoResponse
type ResponseApiKeyInfoResponse struct {
	Data *ModelsApiKeyInfo `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewResponseApiKeyInfoResponse instantiates a new ResponseApiKeyInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseApiKeyInfoResponse() *ResponseApiKeyInfoResponse {
	this := ResponseApiKeyInfoResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// NewResponseApiKeyInfoResponseWithDefaults instantiates a new ResponseApiKeyInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseApiKeyInfoResponseWithDefaults() *ResponseApiKeyInfoResponse {
	this := ResponseApiKeyInfoResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponseApiKeyInfoResponse) GetData() ModelsApiKeyInfo {
	if o == nil || IsNil(o.Data) {
		var ret ModelsApiKeyInfo
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseApiKeyInfoResponse) GetDataOk() (*ModelsApiKeyInfo, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseApiKeyInfoResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ModelsApiKeyInfo and assigns it to the Data field.
func (o *ResponseApiKeyInfoResponse) SetData(v ModelsApiKeyInfo) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseApiKeyInfoResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseApiKeyInfoResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseApiKeyInfoResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseApiKeyInfoResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponseApiKeyInfoResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseApiKeyInfoResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponseApiKeyInfoResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ResponseApiKeyInfoResponse) SetStatus(v string) {
	o.Status = &v
}

func (o ResponseApiKeyInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseApiKeyInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResponseApiKeyInfoResponse struct {
	value *ResponseApiKeyInfoResponse
	isSet bool
}

func (v NullableResponseApiKeyInfoResponse) Get() *ResponseApiKeyInfoResponse {
	return v.value
}

func (v *NullableResponseApiKeyInfoResponse) Set(val *ResponseApiKeyInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseApiKeyInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseApiKeyInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseApiKeyInfoResponse(val *ResponseApiKeyInfoResponse) *NullableResponseApiKeyInfoResponse {
	return &NullableResponseApiKeyInfoResponse{value: val, isSet: true}
}

func (v NullableResponseApiKeyInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseApiKeyInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


