/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozaiplatformgosdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestCheckValidToVerifyAiModelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestCheckValidToVerifyAiModelRequest{}

// RequestCheckValidToVerifyAiModelRequest struct for RequestCheckValidToVerifyAiModelRequest
type RequestCheckValidToVerifyAiModelRequest struct {
	CommitHash string `json:"commit_hash"`
	Platforms []string `json:"platforms"`
}

type _RequestCheckValidToVerifyAiModelRequest RequestCheckValidToVerifyAiModelRequest

// NewRequestCheckValidToVerifyAiModelRequest instantiates a new RequestCheckValidToVerifyAiModelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestCheckValidToVerifyAiModelRequest(commitHash string, platforms []string) *RequestCheckValidToVerifyAiModelRequest {
	this := RequestCheckValidToVerifyAiModelRequest{}
	this.CommitHash = commitHash
	this.Platforms = platforms
	return &this
}

// NewRequestCheckValidToVerifyAiModelRequestWithDefaults instantiates a new RequestCheckValidToVerifyAiModelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestCheckValidToVerifyAiModelRequestWithDefaults() *RequestCheckValidToVerifyAiModelRequest {
	this := RequestCheckValidToVerifyAiModelRequest{}
	return &this
}

// GetCommitHash returns the CommitHash field value
func (o *RequestCheckValidToVerifyAiModelRequest) GetCommitHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommitHash
}

// GetCommitHashOk returns a tuple with the CommitHash field value
// and a boolean to check if the value has been set.
func (o *RequestCheckValidToVerifyAiModelRequest) GetCommitHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommitHash, true
}

// SetCommitHash sets field value
func (o *RequestCheckValidToVerifyAiModelRequest) SetCommitHash(v string) {
	o.CommitHash = v
}

// GetPlatforms returns the Platforms field value
func (o *RequestCheckValidToVerifyAiModelRequest) GetPlatforms() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Platforms
}

// GetPlatformsOk returns a tuple with the Platforms field value
// and a boolean to check if the value has been set.
func (o *RequestCheckValidToVerifyAiModelRequest) GetPlatformsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Platforms, true
}

// SetPlatforms sets field value
func (o *RequestCheckValidToVerifyAiModelRequest) SetPlatforms(v []string) {
	o.Platforms = v
}

func (o RequestCheckValidToVerifyAiModelRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestCheckValidToVerifyAiModelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["commit_hash"] = o.CommitHash
	toSerialize["platforms"] = o.Platforms
	return toSerialize, nil
}

func (o *RequestCheckValidToVerifyAiModelRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"commit_hash",
		"platforms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestCheckValidToVerifyAiModelRequest := _RequestCheckValidToVerifyAiModelRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestCheckValidToVerifyAiModelRequest)

	if err != nil {
		return err
	}

	*o = RequestCheckValidToVerifyAiModelRequest(varRequestCheckValidToVerifyAiModelRequest)

	return err
}

type NullableRequestCheckValidToVerifyAiModelRequest struct {
	value *RequestCheckValidToVerifyAiModelRequest
	isSet bool
}

func (v NullableRequestCheckValidToVerifyAiModelRequest) Get() *RequestCheckValidToVerifyAiModelRequest {
	return v.value
}

func (v *NullableRequestCheckValidToVerifyAiModelRequest) Set(val *RequestCheckValidToVerifyAiModelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestCheckValidToVerifyAiModelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestCheckValidToVerifyAiModelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestCheckValidToVerifyAiModelRequest(val *RequestCheckValidToVerifyAiModelRequest) *NullableRequestCheckValidToVerifyAiModelRequest {
	return &NullableRequestCheckValidToVerifyAiModelRequest{value: val, isSet: true}
}

func (v NullableRequestCheckValidToVerifyAiModelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestCheckValidToVerifyAiModelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


