/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozaiplatformgosdk

import (
	"encoding/json"
)

// checks if the ResponseGetListModelVersioningsLiteData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseGetListModelVersioningsLiteData{}

// ResponseGetListModelVersioningsLiteData struct for ResponseGetListModelVersioningsLiteData
type ResponseGetListModelVersioningsLiteData struct {
	Records []ModelsModelVersioningGroupLite `json:"records,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewResponseGetListModelVersioningsLiteData instantiates a new ResponseGetListModelVersioningsLiteData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseGetListModelVersioningsLiteData() *ResponseGetListModelVersioningsLiteData {
	this := ResponseGetListModelVersioningsLiteData{}
	return &this
}

// NewResponseGetListModelVersioningsLiteDataWithDefaults instantiates a new ResponseGetListModelVersioningsLiteData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseGetListModelVersioningsLiteDataWithDefaults() *ResponseGetListModelVersioningsLiteData {
	this := ResponseGetListModelVersioningsLiteData{}
	return &this
}

// GetRecords returns the Records field value if set, zero value otherwise.
func (o *ResponseGetListModelVersioningsLiteData) GetRecords() []ModelsModelVersioningGroupLite {
	if o == nil || IsNil(o.Records) {
		var ret []ModelsModelVersioningGroupLite
		return ret
	}
	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetListModelVersioningsLiteData) GetRecordsOk() ([]ModelsModelVersioningGroupLite, bool) {
	if o == nil || IsNil(o.Records) {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *ResponseGetListModelVersioningsLiteData) HasRecords() bool {
	if o != nil && !IsNil(o.Records) {
		return true
	}

	return false
}

// SetRecords gets a reference to the given []ModelsModelVersioningGroupLite and assigns it to the Records field.
func (o *ResponseGetListModelVersioningsLiteData) SetRecords(v []ModelsModelVersioningGroupLite) {
	o.Records = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ResponseGetListModelVersioningsLiteData) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetListModelVersioningsLiteData) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ResponseGetListModelVersioningsLiteData) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ResponseGetListModelVersioningsLiteData) SetTotal(v int32) {
	o.Total = &v
}

func (o ResponseGetListModelVersioningsLiteData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseGetListModelVersioningsLiteData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Records) {
		toSerialize["records"] = o.Records
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableResponseGetListModelVersioningsLiteData struct {
	value *ResponseGetListModelVersioningsLiteData
	isSet bool
}

func (v NullableResponseGetListModelVersioningsLiteData) Get() *ResponseGetListModelVersioningsLiteData {
	return v.value
}

func (v *NullableResponseGetListModelVersioningsLiteData) Set(val *ResponseGetListModelVersioningsLiteData) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseGetListModelVersioningsLiteData) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseGetListModelVersioningsLiteData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseGetListModelVersioningsLiteData(val *ResponseGetListModelVersioningsLiteData) *NullableResponseGetListModelVersioningsLiteData {
	return &NullableResponseGetListModelVersioningsLiteData{value: val, isSet: true}
}

func (v NullableResponseGetListModelVersioningsLiteData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseGetListModelVersioningsLiteData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


