/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozaiplatformgosdk

import (
	"encoding/json"
)

// checks if the ResponseModelVersioningResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseModelVersioningResponse{}

// ResponseModelVersioningResponse struct for ResponseModelVersioningResponse
type ResponseModelVersioningResponse struct {
	Data *ModelsModelVersioning `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewResponseModelVersioningResponse instantiates a new ResponseModelVersioningResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseModelVersioningResponse() *ResponseModelVersioningResponse {
	this := ResponseModelVersioningResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// NewResponseModelVersioningResponseWithDefaults instantiates a new ResponseModelVersioningResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseModelVersioningResponseWithDefaults() *ResponseModelVersioningResponse {
	this := ResponseModelVersioningResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponseModelVersioningResponse) GetData() ModelsModelVersioning {
	if o == nil || IsNil(o.Data) {
		var ret ModelsModelVersioning
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseModelVersioningResponse) GetDataOk() (*ModelsModelVersioning, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseModelVersioningResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ModelsModelVersioning and assigns it to the Data field.
func (o *ResponseModelVersioningResponse) SetData(v ModelsModelVersioning) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseModelVersioningResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseModelVersioningResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseModelVersioningResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseModelVersioningResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponseModelVersioningResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseModelVersioningResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponseModelVersioningResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ResponseModelVersioningResponse) SetStatus(v string) {
	o.Status = &v
}

func (o ResponseModelVersioningResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseModelVersioningResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResponseModelVersioningResponse struct {
	value *ResponseModelVersioningResponse
	isSet bool
}

func (v NullableResponseModelVersioningResponse) Get() *ResponseModelVersioningResponse {
	return v.value
}

func (v *NullableResponseModelVersioningResponse) Set(val *ResponseModelVersioningResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseModelVersioningResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseModelVersioningResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseModelVersioningResponse(val *ResponseModelVersioningResponse) *NullableResponseModelVersioningResponse {
	return &NullableResponseModelVersioningResponse{value: val, isSet: true}
}

func (v NullableResponseModelVersioningResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseModelVersioningResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


