/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozaiplatformgosdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestVerifyAiModelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestVerifyAiModelRequest{}

// RequestVerifyAiModelRequest struct for RequestVerifyAiModelRequest
type RequestVerifyAiModelRequest struct {
	CommitHash *string `json:"commit_hash,omitempty"`
	Platforms []string `json:"platforms"`
}

type _RequestVerifyAiModelRequest RequestVerifyAiModelRequest

// NewRequestVerifyAiModelRequest instantiates a new RequestVerifyAiModelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestVerifyAiModelRequest(platforms []string) *RequestVerifyAiModelRequest {
	this := RequestVerifyAiModelRequest{}
	this.Platforms = platforms
	return &this
}

// NewRequestVerifyAiModelRequestWithDefaults instantiates a new RequestVerifyAiModelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestVerifyAiModelRequestWithDefaults() *RequestVerifyAiModelRequest {
	this := RequestVerifyAiModelRequest{}
	return &this
}

// GetCommitHash returns the CommitHash field value if set, zero value otherwise.
func (o *RequestVerifyAiModelRequest) GetCommitHash() string {
	if o == nil || IsNil(o.CommitHash) {
		var ret string
		return ret
	}
	return *o.CommitHash
}

// GetCommitHashOk returns a tuple with the CommitHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestVerifyAiModelRequest) GetCommitHashOk() (*string, bool) {
	if o == nil || IsNil(o.CommitHash) {
		return nil, false
	}
	return o.CommitHash, true
}

// HasCommitHash returns a boolean if a field has been set.
func (o *RequestVerifyAiModelRequest) HasCommitHash() bool {
	if o != nil && !IsNil(o.CommitHash) {
		return true
	}

	return false
}

// SetCommitHash gets a reference to the given string and assigns it to the CommitHash field.
func (o *RequestVerifyAiModelRequest) SetCommitHash(v string) {
	o.CommitHash = &v
}

// GetPlatforms returns the Platforms field value
func (o *RequestVerifyAiModelRequest) GetPlatforms() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Platforms
}

// GetPlatformsOk returns a tuple with the Platforms field value
// and a boolean to check if the value has been set.
func (o *RequestVerifyAiModelRequest) GetPlatformsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Platforms, true
}

// SetPlatforms sets field value
func (o *RequestVerifyAiModelRequest) SetPlatforms(v []string) {
	o.Platforms = v
}

func (o RequestVerifyAiModelRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestVerifyAiModelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CommitHash) {
		toSerialize["commit_hash"] = o.CommitHash
	}
	toSerialize["platforms"] = o.Platforms
	return toSerialize, nil
}

func (o *RequestVerifyAiModelRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"platforms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestVerifyAiModelRequest := _RequestVerifyAiModelRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestVerifyAiModelRequest)

	if err != nil {
		return err
	}

	*o = RequestVerifyAiModelRequest(varRequestVerifyAiModelRequest)

	return err
}

type NullableRequestVerifyAiModelRequest struct {
	value *RequestVerifyAiModelRequest
	isSet bool
}

func (v NullableRequestVerifyAiModelRequest) Get() *RequestVerifyAiModelRequest {
	return v.value
}

func (v *NullableRequestVerifyAiModelRequest) Set(val *RequestVerifyAiModelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestVerifyAiModelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestVerifyAiModelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestVerifyAiModelRequest(val *RequestVerifyAiModelRequest) *NullableRequestVerifyAiModelRequest {
	return &NullableRequestVerifyAiModelRequest{value: val, isSet: true}
}

func (v NullableRequestVerifyAiModelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestVerifyAiModelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


