/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozaiplatformgosdk

import (
	"encoding/json"
)

// checks if the ResponseFailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseFailResponse{}

// ResponseFailResponse struct for ResponseFailResponse
type ResponseFailResponse struct {
	Message *string `json:"message,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewResponseFailResponse instantiates a new ResponseFailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseFailResponse() *ResponseFailResponse {
	this := ResponseFailResponse{}
	var status string = "fail"
	this.Status = &status
	return &this
}

// NewResponseFailResponseWithDefaults instantiates a new ResponseFailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseFailResponseWithDefaults() *ResponseFailResponse {
	this := ResponseFailResponse{}
	var status string = "fail"
	this.Status = &status
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseFailResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseFailResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseFailResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseFailResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponseFailResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseFailResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponseFailResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ResponseFailResponse) SetStatus(v string) {
	o.Status = &v
}

func (o ResponseFailResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseFailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResponseFailResponse struct {
	value *ResponseFailResponse
	isSet bool
}

func (v NullableResponseFailResponse) Get() *ResponseFailResponse {
	return v.value
}

func (v *NullableResponseFailResponse) Set(val *ResponseFailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseFailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseFailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseFailResponse(val *ResponseFailResponse) *NullableResponseFailResponse {
	return &NullableResponseFailResponse{value: val, isSet: true}
}

func (v NullableResponseFailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseFailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


