/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozaiplatformgosdk

import (
	"encoding/json"
)

// checks if the ResponseGetCommitHistoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseGetCommitHistoryResponse{}

// ResponseGetCommitHistoryResponse struct for ResponseGetCommitHistoryResponse
type ResponseGetCommitHistoryResponse struct {
	Data *ResponseGetCommitHistoryData `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewResponseGetCommitHistoryResponse instantiates a new ResponseGetCommitHistoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseGetCommitHistoryResponse() *ResponseGetCommitHistoryResponse {
	this := ResponseGetCommitHistoryResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// NewResponseGetCommitHistoryResponseWithDefaults instantiates a new ResponseGetCommitHistoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseGetCommitHistoryResponseWithDefaults() *ResponseGetCommitHistoryResponse {
	this := ResponseGetCommitHistoryResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponseGetCommitHistoryResponse) GetData() ResponseGetCommitHistoryData {
	if o == nil || IsNil(o.Data) {
		var ret ResponseGetCommitHistoryData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetCommitHistoryResponse) GetDataOk() (*ResponseGetCommitHistoryData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseGetCommitHistoryResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ResponseGetCommitHistoryData and assigns it to the Data field.
func (o *ResponseGetCommitHistoryResponse) SetData(v ResponseGetCommitHistoryData) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseGetCommitHistoryResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetCommitHistoryResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseGetCommitHistoryResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseGetCommitHistoryResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponseGetCommitHistoryResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetCommitHistoryResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponseGetCommitHistoryResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ResponseGetCommitHistoryResponse) SetStatus(v string) {
	o.Status = &v
}

func (o ResponseGetCommitHistoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseGetCommitHistoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResponseGetCommitHistoryResponse struct {
	value *ResponseGetCommitHistoryResponse
	isSet bool
}

func (v NullableResponseGetCommitHistoryResponse) Get() *ResponseGetCommitHistoryResponse {
	return v.value
}

func (v *NullableResponseGetCommitHistoryResponse) Set(val *ResponseGetCommitHistoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseGetCommitHistoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseGetCommitHistoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseGetCommitHistoryResponse(val *ResponseGetCommitHistoryResponse) *NullableResponseGetCommitHistoryResponse {
	return &NullableResponseGetCommitHistoryResponse{value: val, isSet: true}
}

func (v NullableResponseGetCommitHistoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseGetCommitHistoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


