/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package myclient

import (
	"encoding/json"
)

// checks if the ResponseCheckValidToVerifyAiModelResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCheckValidToVerifyAiModelResponse{}

// ResponseCheckValidToVerifyAiModelResponse struct for ResponseCheckValidToVerifyAiModelResponse
type ResponseCheckValidToVerifyAiModelResponse struct {
	Data *ResponseCheckValidToVerifyAiModelData `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewResponseCheckValidToVerifyAiModelResponse instantiates a new ResponseCheckValidToVerifyAiModelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCheckValidToVerifyAiModelResponse() *ResponseCheckValidToVerifyAiModelResponse {
	this := ResponseCheckValidToVerifyAiModelResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// NewResponseCheckValidToVerifyAiModelResponseWithDefaults instantiates a new ResponseCheckValidToVerifyAiModelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCheckValidToVerifyAiModelResponseWithDefaults() *ResponseCheckValidToVerifyAiModelResponse {
	this := ResponseCheckValidToVerifyAiModelResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponseCheckValidToVerifyAiModelResponse) GetData() ResponseCheckValidToVerifyAiModelData {
	if o == nil || IsNil(o.Data) {
		var ret ResponseCheckValidToVerifyAiModelData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckValidToVerifyAiModelResponse) GetDataOk() (*ResponseCheckValidToVerifyAiModelData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseCheckValidToVerifyAiModelResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ResponseCheckValidToVerifyAiModelData and assigns it to the Data field.
func (o *ResponseCheckValidToVerifyAiModelResponse) SetData(v ResponseCheckValidToVerifyAiModelData) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseCheckValidToVerifyAiModelResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckValidToVerifyAiModelResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseCheckValidToVerifyAiModelResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseCheckValidToVerifyAiModelResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponseCheckValidToVerifyAiModelResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckValidToVerifyAiModelResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponseCheckValidToVerifyAiModelResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ResponseCheckValidToVerifyAiModelResponse) SetStatus(v string) {
	o.Status = &v
}

func (o ResponseCheckValidToVerifyAiModelResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCheckValidToVerifyAiModelResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResponseCheckValidToVerifyAiModelResponse struct {
	value *ResponseCheckValidToVerifyAiModelResponse
	isSet bool
}

func (v NullableResponseCheckValidToVerifyAiModelResponse) Get() *ResponseCheckValidToVerifyAiModelResponse {
	return v.value
}

func (v *NullableResponseCheckValidToVerifyAiModelResponse) Set(val *ResponseCheckValidToVerifyAiModelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCheckValidToVerifyAiModelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCheckValidToVerifyAiModelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCheckValidToVerifyAiModelResponse(val *ResponseCheckValidToVerifyAiModelResponse) *NullableResponseCheckValidToVerifyAiModelResponse {
	return &NullableResponseCheckValidToVerifyAiModelResponse{value: val, isSet: true}
}

func (v NullableResponseCheckValidToVerifyAiModelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCheckValidToVerifyAiModelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


