/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package myclient

import (
	"encoding/json"
)

// checks if the ModelsCommitStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsCommitStats{}

// ModelsCommitStats struct for ModelsCommitStats
type ModelsCommitStats struct {
	Additions *int32 `json:"additions,omitempty"`
	Deletions *int32 `json:"deletions,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewModelsCommitStats instantiates a new ModelsCommitStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsCommitStats() *ModelsCommitStats {
	this := ModelsCommitStats{}
	return &this
}

// NewModelsCommitStatsWithDefaults instantiates a new ModelsCommitStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsCommitStatsWithDefaults() *ModelsCommitStats {
	this := ModelsCommitStats{}
	return &this
}

// GetAdditions returns the Additions field value if set, zero value otherwise.
func (o *ModelsCommitStats) GetAdditions() int32 {
	if o == nil || IsNil(o.Additions) {
		var ret int32
		return ret
	}
	return *o.Additions
}

// GetAdditionsOk returns a tuple with the Additions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCommitStats) GetAdditionsOk() (*int32, bool) {
	if o == nil || IsNil(o.Additions) {
		return nil, false
	}
	return o.Additions, true
}

// HasAdditions returns a boolean if a field has been set.
func (o *ModelsCommitStats) HasAdditions() bool {
	if o != nil && !IsNil(o.Additions) {
		return true
	}

	return false
}

// SetAdditions gets a reference to the given int32 and assigns it to the Additions field.
func (o *ModelsCommitStats) SetAdditions(v int32) {
	o.Additions = &v
}

// GetDeletions returns the Deletions field value if set, zero value otherwise.
func (o *ModelsCommitStats) GetDeletions() int32 {
	if o == nil || IsNil(o.Deletions) {
		var ret int32
		return ret
	}
	return *o.Deletions
}

// GetDeletionsOk returns a tuple with the Deletions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCommitStats) GetDeletionsOk() (*int32, bool) {
	if o == nil || IsNil(o.Deletions) {
		return nil, false
	}
	return o.Deletions, true
}

// HasDeletions returns a boolean if a field has been set.
func (o *ModelsCommitStats) HasDeletions() bool {
	if o != nil && !IsNil(o.Deletions) {
		return true
	}

	return false
}

// SetDeletions gets a reference to the given int32 and assigns it to the Deletions field.
func (o *ModelsCommitStats) SetDeletions(v int32) {
	o.Deletions = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ModelsCommitStats) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsCommitStats) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ModelsCommitStats) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ModelsCommitStats) SetTotal(v int32) {
	o.Total = &v
}

func (o ModelsCommitStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsCommitStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Additions) {
		toSerialize["additions"] = o.Additions
	}
	if !IsNil(o.Deletions) {
		toSerialize["deletions"] = o.Deletions
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableModelsCommitStats struct {
	value *ModelsCommitStats
	isSet bool
}

func (v NullableModelsCommitStats) Get() *ModelsCommitStats {
	return v.value
}

func (v *NullableModelsCommitStats) Set(val *ModelsCommitStats) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsCommitStats) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsCommitStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsCommitStats(val *ModelsCommitStats) *NullableModelsCommitStats {
	return &NullableModelsCommitStats{value: val, isSet: true}
}

func (v NullableModelsCommitStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsCommitStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


