/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package myclient

import (
	"encoding/json"
)

// checks if the ResponseGetListPlatformSupportResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseGetListPlatformSupportResponse{}

// ResponseGetListPlatformSupportResponse struct for ResponseGetListPlatformSupportResponse
type ResponseGetListPlatformSupportResponse struct {
	Data []string `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewResponseGetListPlatformSupportResponse instantiates a new ResponseGetListPlatformSupportResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseGetListPlatformSupportResponse() *ResponseGetListPlatformSupportResponse {
	this := ResponseGetListPlatformSupportResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// NewResponseGetListPlatformSupportResponseWithDefaults instantiates a new ResponseGetListPlatformSupportResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseGetListPlatformSupportResponseWithDefaults() *ResponseGetListPlatformSupportResponse {
	this := ResponseGetListPlatformSupportResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponseGetListPlatformSupportResponse) GetData() []string {
	if o == nil || IsNil(o.Data) {
		var ret []string
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetListPlatformSupportResponse) GetDataOk() ([]string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseGetListPlatformSupportResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []string and assigns it to the Data field.
func (o *ResponseGetListPlatformSupportResponse) SetData(v []string) {
	o.Data = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseGetListPlatformSupportResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetListPlatformSupportResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseGetListPlatformSupportResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseGetListPlatformSupportResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponseGetListPlatformSupportResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetListPlatformSupportResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponseGetListPlatformSupportResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ResponseGetListPlatformSupportResponse) SetStatus(v string) {
	o.Status = &v
}

func (o ResponseGetListPlatformSupportResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseGetListPlatformSupportResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResponseGetListPlatformSupportResponse struct {
	value *ResponseGetListPlatformSupportResponse
	isSet bool
}

func (v NullableResponseGetListPlatformSupportResponse) Get() *ResponseGetListPlatformSupportResponse {
	return v.value
}

func (v *NullableResponseGetListPlatformSupportResponse) Set(val *ResponseGetListPlatformSupportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseGetListPlatformSupportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseGetListPlatformSupportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseGetListPlatformSupportResponse(val *ResponseGetListPlatformSupportResponse) *NullableResponseGetListPlatformSupportResponse {
	return &NullableResponseGetListPlatformSupportResponse{value: val, isSet: true}
}

func (v NullableResponseGetListPlatformSupportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseGetListPlatformSupportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


