/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package myclient

import (
	"encoding/json"
)

// checks if the ResponseCheckModelIsServingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCheckModelIsServingResponse{}

// ResponseCheckModelIsServingResponse struct for ResponseCheckModelIsServingResponse
type ResponseCheckModelIsServingResponse struct {
	Data *ResponseCheckModelIsServingData `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewResponseCheckModelIsServingResponse instantiates a new ResponseCheckModelIsServingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCheckModelIsServingResponse() *ResponseCheckModelIsServingResponse {
	this := ResponseCheckModelIsServingResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// NewResponseCheckModelIsServingResponseWithDefaults instantiates a new ResponseCheckModelIsServingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCheckModelIsServingResponseWithDefaults() *ResponseCheckModelIsServingResponse {
	this := ResponseCheckModelIsServingResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponseCheckModelIsServingResponse) GetData() ResponseCheckModelIsServingData {
	if o == nil || IsNil(o.Data) {
		var ret ResponseCheckModelIsServingData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckModelIsServingResponse) GetDataOk() (*ResponseCheckModelIsServingData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseCheckModelIsServingResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ResponseCheckModelIsServingData and assigns it to the Data field.
func (o *ResponseCheckModelIsServingResponse) SetData(v ResponseCheckModelIsServingData) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseCheckModelIsServingResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckModelIsServingResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseCheckModelIsServingResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseCheckModelIsServingResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponseCheckModelIsServingResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckModelIsServingResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponseCheckModelIsServingResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ResponseCheckModelIsServingResponse) SetStatus(v string) {
	o.Status = &v
}

func (o ResponseCheckModelIsServingResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCheckModelIsServingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResponseCheckModelIsServingResponse struct {
	value *ResponseCheckModelIsServingResponse
	isSet bool
}

func (v NullableResponseCheckModelIsServingResponse) Get() *ResponseCheckModelIsServingResponse {
	return v.value
}

func (v *NullableResponseCheckModelIsServingResponse) Set(val *ResponseCheckModelIsServingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCheckModelIsServingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCheckModelIsServingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCheckModelIsServingResponse(val *ResponseCheckModelIsServingResponse) *NullableResponseCheckModelIsServingResponse {
	return &NullableResponseCheckModelIsServingResponse{value: val, isSet: true}
}

func (v NullableResponseCheckModelIsServingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCheckModelIsServingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


