/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package myclient

import (
	"encoding/json"
)

// checks if the ModelsWalletWithAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsWalletWithAddress{}

// ModelsWalletWithAddress struct for ModelsWalletWithAddress
type ModelsWalletWithAddress struct {
	Balance *float32 `json:"balance,omitempty"`
	Debt *float32 `json:"debt,omitempty"`
	Earnings *float32 `json:"earnings,omitempty"`
	FreeBalance *float32 `json:"free_balance,omitempty"`
	WalletAddress *string `json:"wallet_address,omitempty"`
}

// NewModelsWalletWithAddress instantiates a new ModelsWalletWithAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsWalletWithAddress() *ModelsWalletWithAddress {
	this := ModelsWalletWithAddress{}
	return &this
}

// NewModelsWalletWithAddressWithDefaults instantiates a new ModelsWalletWithAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsWalletWithAddressWithDefaults() *ModelsWalletWithAddress {
	this := ModelsWalletWithAddress{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *ModelsWalletWithAddress) GetBalance() float32 {
	if o == nil || IsNil(o.Balance) {
		var ret float32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWalletWithAddress) GetBalanceOk() (*float32, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *ModelsWalletWithAddress) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given float32 and assigns it to the Balance field.
func (o *ModelsWalletWithAddress) SetBalance(v float32) {
	o.Balance = &v
}

// GetDebt returns the Debt field value if set, zero value otherwise.
func (o *ModelsWalletWithAddress) GetDebt() float32 {
	if o == nil || IsNil(o.Debt) {
		var ret float32
		return ret
	}
	return *o.Debt
}

// GetDebtOk returns a tuple with the Debt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWalletWithAddress) GetDebtOk() (*float32, bool) {
	if o == nil || IsNil(o.Debt) {
		return nil, false
	}
	return o.Debt, true
}

// HasDebt returns a boolean if a field has been set.
func (o *ModelsWalletWithAddress) HasDebt() bool {
	if o != nil && !IsNil(o.Debt) {
		return true
	}

	return false
}

// SetDebt gets a reference to the given float32 and assigns it to the Debt field.
func (o *ModelsWalletWithAddress) SetDebt(v float32) {
	o.Debt = &v
}

// GetEarnings returns the Earnings field value if set, zero value otherwise.
func (o *ModelsWalletWithAddress) GetEarnings() float32 {
	if o == nil || IsNil(o.Earnings) {
		var ret float32
		return ret
	}
	return *o.Earnings
}

// GetEarningsOk returns a tuple with the Earnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWalletWithAddress) GetEarningsOk() (*float32, bool) {
	if o == nil || IsNil(o.Earnings) {
		return nil, false
	}
	return o.Earnings, true
}

// HasEarnings returns a boolean if a field has been set.
func (o *ModelsWalletWithAddress) HasEarnings() bool {
	if o != nil && !IsNil(o.Earnings) {
		return true
	}

	return false
}

// SetEarnings gets a reference to the given float32 and assigns it to the Earnings field.
func (o *ModelsWalletWithAddress) SetEarnings(v float32) {
	o.Earnings = &v
}

// GetFreeBalance returns the FreeBalance field value if set, zero value otherwise.
func (o *ModelsWalletWithAddress) GetFreeBalance() float32 {
	if o == nil || IsNil(o.FreeBalance) {
		var ret float32
		return ret
	}
	return *o.FreeBalance
}

// GetFreeBalanceOk returns a tuple with the FreeBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWalletWithAddress) GetFreeBalanceOk() (*float32, bool) {
	if o == nil || IsNil(o.FreeBalance) {
		return nil, false
	}
	return o.FreeBalance, true
}

// HasFreeBalance returns a boolean if a field has been set.
func (o *ModelsWalletWithAddress) HasFreeBalance() bool {
	if o != nil && !IsNil(o.FreeBalance) {
		return true
	}

	return false
}

// SetFreeBalance gets a reference to the given float32 and assigns it to the FreeBalance field.
func (o *ModelsWalletWithAddress) SetFreeBalance(v float32) {
	o.FreeBalance = &v
}

// GetWalletAddress returns the WalletAddress field value if set, zero value otherwise.
func (o *ModelsWalletWithAddress) GetWalletAddress() string {
	if o == nil || IsNil(o.WalletAddress) {
		var ret string
		return ret
	}
	return *o.WalletAddress
}

// GetWalletAddressOk returns a tuple with the WalletAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWalletWithAddress) GetWalletAddressOk() (*string, bool) {
	if o == nil || IsNil(o.WalletAddress) {
		return nil, false
	}
	return o.WalletAddress, true
}

// HasWalletAddress returns a boolean if a field has been set.
func (o *ModelsWalletWithAddress) HasWalletAddress() bool {
	if o != nil && !IsNil(o.WalletAddress) {
		return true
	}

	return false
}

// SetWalletAddress gets a reference to the given string and assigns it to the WalletAddress field.
func (o *ModelsWalletWithAddress) SetWalletAddress(v string) {
	o.WalletAddress = &v
}

func (o ModelsWalletWithAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsWalletWithAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.Debt) {
		toSerialize["debt"] = o.Debt
	}
	if !IsNil(o.Earnings) {
		toSerialize["earnings"] = o.Earnings
	}
	if !IsNil(o.FreeBalance) {
		toSerialize["free_balance"] = o.FreeBalance
	}
	if !IsNil(o.WalletAddress) {
		toSerialize["wallet_address"] = o.WalletAddress
	}
	return toSerialize, nil
}

type NullableModelsWalletWithAddress struct {
	value *ModelsWalletWithAddress
	isSet bool
}

func (v NullableModelsWalletWithAddress) Get() *ModelsWalletWithAddress {
	return v.value
}

func (v *NullableModelsWalletWithAddress) Set(val *ModelsWalletWithAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsWalletWithAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsWalletWithAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsWalletWithAddress(val *ModelsWalletWithAddress) *NullableModelsWalletWithAddress {
	return &NullableModelsWalletWithAddress{value: val, isSet: true}
}

func (v NullableModelsWalletWithAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsWalletWithAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


