/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package myclient

import (
	"encoding/json"
)

// checks if the ResponseEstimateCostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseEstimateCostResponse{}

// ResponseEstimateCostResponse struct for ResponseEstimateCostResponse
type ResponseEstimateCostResponse struct {
	Data *ResponseEstimateCostData `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewResponseEstimateCostResponse instantiates a new ResponseEstimateCostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseEstimateCostResponse() *ResponseEstimateCostResponse {
	this := ResponseEstimateCostResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// NewResponseEstimateCostResponseWithDefaults instantiates a new ResponseEstimateCostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseEstimateCostResponseWithDefaults() *ResponseEstimateCostResponse {
	this := ResponseEstimateCostResponse{}
	var status string = "success"
	this.Status = &status
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponseEstimateCostResponse) GetData() ResponseEstimateCostData {
	if o == nil || IsNil(o.Data) {
		var ret ResponseEstimateCostData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseEstimateCostResponse) GetDataOk() (*ResponseEstimateCostData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseEstimateCostResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ResponseEstimateCostData and assigns it to the Data field.
func (o *ResponseEstimateCostResponse) SetData(v ResponseEstimateCostData) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseEstimateCostResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseEstimateCostResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseEstimateCostResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseEstimateCostResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponseEstimateCostResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseEstimateCostResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponseEstimateCostResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ResponseEstimateCostResponse) SetStatus(v string) {
	o.Status = &v
}

func (o ResponseEstimateCostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseEstimateCostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResponseEstimateCostResponse struct {
	value *ResponseEstimateCostResponse
	isSet bool
}

func (v NullableResponseEstimateCostResponse) Get() *ResponseEstimateCostResponse {
	return v.value
}

func (v *NullableResponseEstimateCostResponse) Set(val *ResponseEstimateCostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseEstimateCostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseEstimateCostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseEstimateCostResponse(val *ResponseEstimateCostResponse) *NullableResponseEstimateCostResponse {
	return &NullableResponseEstimateCostResponse{value: val, isSet: true}
}

func (v NullableResponseEstimateCostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseEstimateCostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


