/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package myclient

import (
	"encoding/json"
)

// checks if the RequestDistributeTaskRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestDistributeTaskRequest{}

// RequestDistributeTaskRequest struct for RequestDistributeTaskRequest
type RequestDistributeTaskRequest struct {
	Files []map[string]interface{} `json:"files,omitempty"`
	InputParams map[string]interface{} `json:"input_params,omitempty"`
	ModelId *string `json:"model_id,omitempty"`
}

// NewRequestDistributeTaskRequest instantiates a new RequestDistributeTaskRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestDistributeTaskRequest() *RequestDistributeTaskRequest {
	this := RequestDistributeTaskRequest{}
	return &this
}

// NewRequestDistributeTaskRequestWithDefaults instantiates a new RequestDistributeTaskRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestDistributeTaskRequestWithDefaults() *RequestDistributeTaskRequest {
	this := RequestDistributeTaskRequest{}
	return &this
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *RequestDistributeTaskRequest) GetFiles() []map[string]interface{} {
	if o == nil || IsNil(o.Files) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestDistributeTaskRequest) GetFilesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *RequestDistributeTaskRequest) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []map[string]interface{} and assigns it to the Files field.
func (o *RequestDistributeTaskRequest) SetFiles(v []map[string]interface{}) {
	o.Files = v
}

// GetInputParams returns the InputParams field value if set, zero value otherwise.
func (o *RequestDistributeTaskRequest) GetInputParams() map[string]interface{} {
	if o == nil || IsNil(o.InputParams) {
		var ret map[string]interface{}
		return ret
	}
	return o.InputParams
}

// GetInputParamsOk returns a tuple with the InputParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestDistributeTaskRequest) GetInputParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.InputParams) {
		return map[string]interface{}{}, false
	}
	return o.InputParams, true
}

// HasInputParams returns a boolean if a field has been set.
func (o *RequestDistributeTaskRequest) HasInputParams() bool {
	if o != nil && !IsNil(o.InputParams) {
		return true
	}

	return false
}

// SetInputParams gets a reference to the given map[string]interface{} and assigns it to the InputParams field.
func (o *RequestDistributeTaskRequest) SetInputParams(v map[string]interface{}) {
	o.InputParams = v
}

// GetModelId returns the ModelId field value if set, zero value otherwise.
func (o *RequestDistributeTaskRequest) GetModelId() string {
	if o == nil || IsNil(o.ModelId) {
		var ret string
		return ret
	}
	return *o.ModelId
}

// GetModelIdOk returns a tuple with the ModelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestDistributeTaskRequest) GetModelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ModelId) {
		return nil, false
	}
	return o.ModelId, true
}

// HasModelId returns a boolean if a field has been set.
func (o *RequestDistributeTaskRequest) HasModelId() bool {
	if o != nil && !IsNil(o.ModelId) {
		return true
	}

	return false
}

// SetModelId gets a reference to the given string and assigns it to the ModelId field.
func (o *RequestDistributeTaskRequest) SetModelId(v string) {
	o.ModelId = &v
}

func (o RequestDistributeTaskRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestDistributeTaskRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	if !IsNil(o.InputParams) {
		toSerialize["input_params"] = o.InputParams
	}
	if !IsNil(o.ModelId) {
		toSerialize["model_id"] = o.ModelId
	}
	return toSerialize, nil
}

type NullableRequestDistributeTaskRequest struct {
	value *RequestDistributeTaskRequest
	isSet bool
}

func (v NullableRequestDistributeTaskRequest) Get() *RequestDistributeTaskRequest {
	return v.value
}

func (v *NullableRequestDistributeTaskRequest) Set(val *RequestDistributeTaskRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestDistributeTaskRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestDistributeTaskRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestDistributeTaskRequest(val *RequestDistributeTaskRequest) *NullableRequestDistributeTaskRequest {
	return &NullableRequestDistributeTaskRequest{value: val, isSet: true}
}

func (v NullableRequestDistributeTaskRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestDistributeTaskRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


