/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package myclient

import (
	"encoding/json"
)

// checks if the ResponseModelVersioningGroupLiteListData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseModelVersioningGroupLiteListData{}

// ResponseModelVersioningGroupLiteListData struct for ResponseModelVersioningGroupLiteListData
type ResponseModelVersioningGroupLiteListData struct {
	Records []ModelsModelVersioningGroupLite `json:"records,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewResponseModelVersioningGroupLiteListData instantiates a new ResponseModelVersioningGroupLiteListData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseModelVersioningGroupLiteListData() *ResponseModelVersioningGroupLiteListData {
	this := ResponseModelVersioningGroupLiteListData{}
	return &this
}

// NewResponseModelVersioningGroupLiteListDataWithDefaults instantiates a new ResponseModelVersioningGroupLiteListData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseModelVersioningGroupLiteListDataWithDefaults() *ResponseModelVersioningGroupLiteListData {
	this := ResponseModelVersioningGroupLiteListData{}
	return &this
}

// GetRecords returns the Records field value if set, zero value otherwise.
func (o *ResponseModelVersioningGroupLiteListData) GetRecords() []ModelsModelVersioningGroupLite {
	if o == nil || IsNil(o.Records) {
		var ret []ModelsModelVersioningGroupLite
		return ret
	}
	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseModelVersioningGroupLiteListData) GetRecordsOk() ([]ModelsModelVersioningGroupLite, bool) {
	if o == nil || IsNil(o.Records) {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *ResponseModelVersioningGroupLiteListData) HasRecords() bool {
	if o != nil && !IsNil(o.Records) {
		return true
	}

	return false
}

// SetRecords gets a reference to the given []ModelsModelVersioningGroupLite and assigns it to the Records field.
func (o *ResponseModelVersioningGroupLiteListData) SetRecords(v []ModelsModelVersioningGroupLite) {
	o.Records = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ResponseModelVersioningGroupLiteListData) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseModelVersioningGroupLiteListData) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ResponseModelVersioningGroupLiteListData) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ResponseModelVersioningGroupLiteListData) SetTotal(v int32) {
	o.Total = &v
}

func (o ResponseModelVersioningGroupLiteListData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseModelVersioningGroupLiteListData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Records) {
		toSerialize["records"] = o.Records
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableResponseModelVersioningGroupLiteListData struct {
	value *ResponseModelVersioningGroupLiteListData
	isSet bool
}

func (v NullableResponseModelVersioningGroupLiteListData) Get() *ResponseModelVersioningGroupLiteListData {
	return v.value
}

func (v *NullableResponseModelVersioningGroupLiteListData) Set(val *ResponseModelVersioningGroupLiteListData) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseModelVersioningGroupLiteListData) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseModelVersioningGroupLiteListData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseModelVersioningGroupLiteListData(val *ResponseModelVersioningGroupLiteListData) *NullableResponseModelVersioningGroupLiteListData {
	return &NullableResponseModelVersioningGroupLiteListData{value: val, isSet: true}
}

func (v NullableResponseModelVersioningGroupLiteListData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseModelVersioningGroupLiteListData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


