/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package myclient

import (
	"encoding/json"
)

// checks if the ResponseGetApiKeyPermissionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseGetApiKeyPermissionData{}

// ResponseGetApiKeyPermissionData struct for ResponseGetApiKeyPermissionData
type ResponseGetApiKeyPermissionData struct {
	ApiKeyPackages []ModelsApiKeyPackage `json:"api_key_packages,omitempty"`
	LimitModels *bool `json:"limit_models,omitempty"`
	Models []string `json:"models,omitempty"`
}

// NewResponseGetApiKeyPermissionData instantiates a new ResponseGetApiKeyPermissionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseGetApiKeyPermissionData() *ResponseGetApiKeyPermissionData {
	this := ResponseGetApiKeyPermissionData{}
	return &this
}

// NewResponseGetApiKeyPermissionDataWithDefaults instantiates a new ResponseGetApiKeyPermissionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseGetApiKeyPermissionDataWithDefaults() *ResponseGetApiKeyPermissionData {
	this := ResponseGetApiKeyPermissionData{}
	return &this
}

// GetApiKeyPackages returns the ApiKeyPackages field value if set, zero value otherwise.
func (o *ResponseGetApiKeyPermissionData) GetApiKeyPackages() []ModelsApiKeyPackage {
	if o == nil || IsNil(o.ApiKeyPackages) {
		var ret []ModelsApiKeyPackage
		return ret
	}
	return o.ApiKeyPackages
}

// GetApiKeyPackagesOk returns a tuple with the ApiKeyPackages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetApiKeyPermissionData) GetApiKeyPackagesOk() ([]ModelsApiKeyPackage, bool) {
	if o == nil || IsNil(o.ApiKeyPackages) {
		return nil, false
	}
	return o.ApiKeyPackages, true
}

// HasApiKeyPackages returns a boolean if a field has been set.
func (o *ResponseGetApiKeyPermissionData) HasApiKeyPackages() bool {
	if o != nil && !IsNil(o.ApiKeyPackages) {
		return true
	}

	return false
}

// SetApiKeyPackages gets a reference to the given []ModelsApiKeyPackage and assigns it to the ApiKeyPackages field.
func (o *ResponseGetApiKeyPermissionData) SetApiKeyPackages(v []ModelsApiKeyPackage) {
	o.ApiKeyPackages = v
}

// GetLimitModels returns the LimitModels field value if set, zero value otherwise.
func (o *ResponseGetApiKeyPermissionData) GetLimitModels() bool {
	if o == nil || IsNil(o.LimitModels) {
		var ret bool
		return ret
	}
	return *o.LimitModels
}

// GetLimitModelsOk returns a tuple with the LimitModels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetApiKeyPermissionData) GetLimitModelsOk() (*bool, bool) {
	if o == nil || IsNil(o.LimitModels) {
		return nil, false
	}
	return o.LimitModels, true
}

// HasLimitModels returns a boolean if a field has been set.
func (o *ResponseGetApiKeyPermissionData) HasLimitModels() bool {
	if o != nil && !IsNil(o.LimitModels) {
		return true
	}

	return false
}

// SetLimitModels gets a reference to the given bool and assigns it to the LimitModels field.
func (o *ResponseGetApiKeyPermissionData) SetLimitModels(v bool) {
	o.LimitModels = &v
}

// GetModels returns the Models field value if set, zero value otherwise.
func (o *ResponseGetApiKeyPermissionData) GetModels() []string {
	if o == nil || IsNil(o.Models) {
		var ret []string
		return ret
	}
	return o.Models
}

// GetModelsOk returns a tuple with the Models field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseGetApiKeyPermissionData) GetModelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Models) {
		return nil, false
	}
	return o.Models, true
}

// HasModels returns a boolean if a field has been set.
func (o *ResponseGetApiKeyPermissionData) HasModels() bool {
	if o != nil && !IsNil(o.Models) {
		return true
	}

	return false
}

// SetModels gets a reference to the given []string and assigns it to the Models field.
func (o *ResponseGetApiKeyPermissionData) SetModels(v []string) {
	o.Models = v
}

func (o ResponseGetApiKeyPermissionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseGetApiKeyPermissionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiKeyPackages) {
		toSerialize["api_key_packages"] = o.ApiKeyPackages
	}
	if !IsNil(o.LimitModels) {
		toSerialize["limit_models"] = o.LimitModels
	}
	if !IsNil(o.Models) {
		toSerialize["models"] = o.Models
	}
	return toSerialize, nil
}

type NullableResponseGetApiKeyPermissionData struct {
	value *ResponseGetApiKeyPermissionData
	isSet bool
}

func (v NullableResponseGetApiKeyPermissionData) Get() *ResponseGetApiKeyPermissionData {
	return v.value
}

func (v *NullableResponseGetApiKeyPermissionData) Set(val *ResponseGetApiKeyPermissionData) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseGetApiKeyPermissionData) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseGetApiKeyPermissionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseGetApiKeyPermissionData(val *ResponseGetApiKeyPermissionData) *NullableResponseGetApiKeyPermissionData {
	return &NullableResponseGetApiKeyPermissionData{value: val, isSet: true}
}

func (v NullableResponseGetApiKeyPermissionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseGetApiKeyPermissionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


