/*
AIOZ-AI-PLATFORM API

API for AIOZ AI Platform

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package myclient

import (
	"encoding/json"
)

// checks if the ResponseCheckValidToVerifyAiModelData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCheckValidToVerifyAiModelData{}

// ResponseCheckValidToVerifyAiModelData struct for ResponseCheckValidToVerifyAiModelData
type ResponseCheckValidToVerifyAiModelData struct {
	Valid *bool `json:"valid,omitempty"`
}

// NewResponseCheckValidToVerifyAiModelData instantiates a new ResponseCheckValidToVerifyAiModelData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCheckValidToVerifyAiModelData() *ResponseCheckValidToVerifyAiModelData {
	this := ResponseCheckValidToVerifyAiModelData{}
	return &this
}

// NewResponseCheckValidToVerifyAiModelDataWithDefaults instantiates a new ResponseCheckValidToVerifyAiModelData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCheckValidToVerifyAiModelDataWithDefaults() *ResponseCheckValidToVerifyAiModelData {
	this := ResponseCheckValidToVerifyAiModelData{}
	return &this
}

// GetValid returns the Valid field value if set, zero value otherwise.
func (o *ResponseCheckValidToVerifyAiModelData) GetValid() bool {
	if o == nil || IsNil(o.Valid) {
		var ret bool
		return ret
	}
	return *o.Valid
}

// GetValidOk returns a tuple with the Valid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckValidToVerifyAiModelData) GetValidOk() (*bool, bool) {
	if o == nil || IsNil(o.Valid) {
		return nil, false
	}
	return o.Valid, true
}

// HasValid returns a boolean if a field has been set.
func (o *ResponseCheckValidToVerifyAiModelData) HasValid() bool {
	if o != nil && !IsNil(o.Valid) {
		return true
	}

	return false
}

// SetValid gets a reference to the given bool and assigns it to the Valid field.
func (o *ResponseCheckValidToVerifyAiModelData) SetValid(v bool) {
	o.Valid = &v
}

func (o ResponseCheckValidToVerifyAiModelData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCheckValidToVerifyAiModelData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Valid) {
		toSerialize["valid"] = o.Valid
	}
	return toSerialize, nil
}

type NullableResponseCheckValidToVerifyAiModelData struct {
	value *ResponseCheckValidToVerifyAiModelData
	isSet bool
}

func (v NullableResponseCheckValidToVerifyAiModelData) Get() *ResponseCheckValidToVerifyAiModelData {
	return v.value
}

func (v *NullableResponseCheckValidToVerifyAiModelData) Set(val *ResponseCheckValidToVerifyAiModelData) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCheckValidToVerifyAiModelData) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCheckValidToVerifyAiModelData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCheckValidToVerifyAiModelData(val *ResponseCheckValidToVerifyAiModelData) *NullableResponseCheckValidToVerifyAiModelData {
	return &NullableResponseCheckValidToVerifyAiModelData{value: val, isSet: true}
}

func (v NullableResponseCheckValidToVerifyAiModelData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCheckValidToVerifyAiModelData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


